# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  heroes = Hero.create([
    { name: 'Belit', description: "Queen of the Black Coast ",
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Belit.jpg',
      life: '9', encumberance: '9',
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Yellow',
      origin: 'Core Game', skill_ids: [6, 13, 16, 21, 28], story_ids: [] },
    { name: 'Conan', description: 'The Cimmerian',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Conan.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Core Game', skill_ids: [4, 11, 13, 16, 19], story_ids: [] },
    { name: 'Hadrathus', description: 'Alcolyte',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Hadrathus.jpg',
      life: '10', encumberance: '8',
      melee_dice: 'Yellow', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '2',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Core Game', skill_ids: [16, 22, 33], story_ids: [] },
    { name: 'Shevatas', description: 'King of Thieves',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shevatus.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Red', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Core Game', skill_ids: [12, 16, 19, 23, 30], story_ids: [] },
    { name: 'Amara The Lion', description: 'King Conan',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Amara.jpg',
      life: '11', encumberance: '11',
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'King Pledge', skill_ids: [7, 13, 16, 21, 22], story_ids: [] },
    { name: "N'Gora", description: "Belit's Second",
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/NGora.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Orange', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '5',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'King Pledge', skill_ids: [8, 13, 16, 19, 31], story_ids: [] },
    { name: 'Valeria', description: 'Bad Ass',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Valeria.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Orange-Reroll', melee_exertion: '3',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'King Pledge', skill_ids: [2, 7, 16], story_ids: [] },
    { name: 'Zelata', description: 'The Witch',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Zelata.jpg',
      life: '9', encumberance: '9',
      melee_dice: 'Yellow', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Yellow',
      origin: 'King Pledge', skill_ids: [16, 20, 21, 22, 28, 33], story_ids: [] },
    { name: 'Amboola', description: 'A Kushite Commander',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Amboola.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Orange', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [5, 13, 16, 21], story_ids: [] },
    { name: 'Balthus', description: 'A scout and a deadeye shot',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Balthus.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange-Reroll', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '2',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [8, 9, 13, 16, 17, 21], story_ids: [] },
    { name: 'Conan - General', description: "",
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ConanGeneral.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Red-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [11, 13, 16, 19, 21], story_ids: [] },
    { name: 'Conan - Mercenary', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ConanMercenary.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [2, 7, 13, 16, 19], story_ids: [] },
    { name: 'Conan - Wanderer', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ConanWanderer.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [4, 11, 13, 16, 19], story_ids: [] },
    { name: 'Conan - Warlord', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ConanWarlord.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Red', melee_exertion: '6',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [4, 13, 16, 19, 22], story_ids: [] },
    { name: 'Kerim Shah', description: 'A Turanian Prince',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KerimShah.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [9, 16, 19, 22, 30], story_ids: [] },
    { name: 'Olgerd Vladislav', description: 'The Tiger',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/OlgerdVladislav.jpg',
      life: '11', encumberance: '11',
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [4, 9, 16, 31], story_ids: [] },
    { name: 'Pallantides', description: 'Captian of the Black Dragons',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pallantides.jpg',
      life: '11', encumberance: '11',
      melee_dice: 'Orange-Reroll', melee_exertion: '5',
      ranged_dice: 'Yellow-Reroll', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '5',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [9, 16, 21, 29, 31], story_ids: [] },
    { name: 'Pelias', description: 'A Dark Sorcerer',
      quote: '',
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pelias.jpg',
      life: '11', encumberance: '9',
      melee_dice: 'Yellow', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Yellow-Reroll',
      origin: 'Stretch Goals', skill_ids: [6, 21, 22, 26, 33], story_ids: [] },
    { name: 'Savage Belit', description: 'Fighting Queen of the Black Coast',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/SavageBelit.jpg',
      life: '10', encumberance: '9',
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Yellow',
      origin: 'Stretch Goals', skill_ids: [2, 6, 12, 13, 16], story_ids: [] },
    { name: 'Taurus', description: 'Prince of Thieves',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Taurus.jpg',
      life: '10', encumberance: '11',
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Red', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [5, 16, 17, 19, 23], story_ids: [] },
    { name: 'Constantius', description: 'The Falcon',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Constantius.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Orange', melee_exertion: '6',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [4, 7, 28, 31], story_ids: [] },
    { name: 'Skuthus', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skuthus.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Yellow', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Yellow',
      origin: 'Stretch Goals', skill_ids: [6, 22, 33], story_ids: [] },
    { name: 'Thak', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thak.jpg',
      life: '14', encumberance: '14',
      melee_dice: 'Red-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Yellow-Reroll',
      origin: 'Stretch Goals', skill_ids: [2, 13, 16, 19], story_ids: [] },
    { name: 'Zaporavo', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Zaporavo.jpg',
      life: '10', encumberance: '12',
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [5, 7, 16, 21, 32], story_ids: [] },
    { name: 'Zogar Sag', description: 'Pict Shaman',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZogarSag.jpg',
      life: '10', encumberance: '8',
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goals', skill_ids: [12, 21, 32, 33], story_ids: [] },
    { name: 'Vanir Valkyrie', description: 'Not Red Sonja',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirValkyrie.jpg',
      life: '10', encumberance: '10',
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '3',
      manipulation_dice: 'Red', manipulation_exersion: '2',
      defense_dice: 'Orange',
      origin: 'Add On', skill_ids: [2, 5, 12, 16, 31], story_ids: [] },
    { name: 'Niord', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Niord.jpg',
      life: '11', encumberance: '12',
      melee_dice: 'Orange', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Red',
      origin: 'Nordheim Expansion', skill_ids: [2, 10, 16, 19, 21], story_ids: [] }
  ])
