# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  Hero.create!([

    # Core Game
    { name: 'Bêlit', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Belit.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BelitSheet.jpg',
      life: '9', encumbrance: ["9", "7", "9", "6", "8"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '5',
      defense_dice: 'Yellow',
      origin: 'Core Game', skill_ids: [13, 16, 21, 28, 6] },

    { name: 'Conan', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Conan.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "9", "11"],
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Core Game', skill_ids: [13, 16, 19, 11, 4] },

    { name: 'Hadrathus', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Hadrathus.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/HadrathusSheet.jpg',
      life: '10', encumbrance: ["8", "5", "7", "5", "5", "5"],
      melee_dice: 'Yellow', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '2',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Core Game', skill_ids: [16, 22, 33] },

    { name: 'Shevatas', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Shevatas.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ShevatasSheet.jpg',
      life: '10', encumbrance: ["10", "6", "9", "5", "6", "8", "8"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Red', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Core Game', skill_ids: [12, 30, 16, 19, 23] },

      # King Pledge
    { name: 'Amra the Lion', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/AmaraTheLion.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/AmratheLionSheet.jpg',
      life: '11', encumbrance: ["11", "10", "11", "6", "7", "8"],
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'King Pledge', skill_ids: [13, 22, 16, 21, 7] },

    { name: "N'Gora", description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/NGora.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/NGoraSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "9", "11"],
      melee_dice: 'Orange', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '5',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'King Pledge', skill_ids: [13, 16, 19, 8, 31] },

    { name: 'Valeria', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Valeria.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ValeriaSheet.jpg',
      life: '10', encumbrance: ["10", "6", "8", "5", "6", "7"],
      melee_dice: 'Orange-Reroll', melee_exertion: '3',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'King Pledge', skill_ids: [16, 2, 7] },

    { name: 'Zelata', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Zelata.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ZelataSheet.jpg',
      life: '9', encumbrance: ["9", "7", "9", "6", "6", "6"],
      melee_dice: 'Yellow', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Yellow',
      origin: 'King Pledge', skill_ids: [16, 33, 22, 28, 20, 21] },

    # Strech Goals
    { name: 'Amboola', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Amboola.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/AmboolaSheet.jpg',
      life: '10', encumbrance: ["10", "9", "10", "6", "7", "9"],
      melee_dice: 'Orange', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [13, 16, 5, 21] },

    { name: 'Balthus', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Balthus.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BalthusSheet.jpg',
      life: '10', encumbrance: ["10", "7", "10", "7", "7", "8", "8", "8"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange-Reroll', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '2',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [17, 13, 8, 9, 16, 21] },

    { name: 'Conan the General', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanGeneral.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanGeneralSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "9", "11"],
      melee_dice: 'Red-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [13, 16, 19, 11, 21] },

    { name: 'Conan Mercenary', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanMercenary.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanMercenarySheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "7", "8", "8", "9"],
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [13, 7, 16, 2, 19] },

    { name: 'Conan the Wanderer', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanWanderer.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanWandererSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "7", "9", "10", "11"],
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [13, 16, 19, 11, 4] },

    { name: 'Conan Warlord', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanWarlord.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanWarlordSheet.jpg',
      life: '11', encumbrance: ["12", "9", "11", "6", "7", "8", "9"],
      melee_dice: 'Red', melee_exertion: '6',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [13, 22, 16, 19, 4] },

    { name: 'Constantius', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Constantius.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConstantiusSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "8", "9", "11"],
      melee_dice: 'Orange', melee_exertion: '6',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [31, 28, 7, 4] },

    { name: 'Kerim Shah', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/KerimShah.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/KerimShahSheet.jpg',
      life: '10', encumbrance: ["10", "9", "10", "7", "7", "8", "9", "10"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [16, 19, 30, 9, 22] },

    { name: 'Olgerd Vladislav', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/OlgerdVladislav.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/OlgerdVladislavSheet.jpg',
      life: '11', encumbrance: ["11", "8", "10", "8", "8", "10"],
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [16, 31, 9, 4] },

    { name: 'Pallantides', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Pallantides.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/PallantidesSheet.jpg',
      life: '11', encumbrance: ["11", "8", "10", "7", "8", "10", "10"],
      melee_dice: 'Orange-Reroll', melee_exertion: '5',
      ranged_dice: 'Yellow-Reroll', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '5',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [16, 9, 31, 29, 21] },

    { name: 'Pelias', description: '',
      quote: '',
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Pelias.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/PeliasSheet.jpg',
      life: '11', encumbrance: ["9", "6", "8", "5", "5"],
      melee_dice: 'Yellow', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '5',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Yellow-Reroll',
      origin: 'Stretch Goal', skill_ids: [33, 22, 6, 26, 21] },

    { name: 'Savage Bêlit', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/SavageBelit.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/SavageBelitSheet.jpg',
      life: '10', encumbrance: ["9", "7", "8", "6", "7", "7", "8"],
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Yellow',
      origin: 'Stretch Goal', skill_ids: [13, 2, 12, 16, 6] },

    { name: 'Taurus', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Taurus.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/TaurusSheet.jpg',
      life: '10', encumbrance: ["11", "8", "10", "6", "6", "6", "8"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Red', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [17, 19, 16, 5, 23] },

    { name: 'Skuthus', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Skuthus.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/SkuthusSheet.jpg',
      life: '10', encumbrance: ["10", "7", "9", "8", "9"],
      melee_dice: 'Yellow', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Yellow',
      origin: 'Stretch Goal', skill_ids: [22, 6, 33] },

    { name: 'Thak', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Thak.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ThakSheet.jpg',
      life: '14', encumbrance: ["14", "10", "12", "9", "10", "11"],
      melee_dice: 'Red-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Yellow-Reroll',
      origin: 'Stretch Goal', skill_ids: [13, 16, 19, 2] },

    { name: 'Zaporavo', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Zaporavo.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ZaporavoSheet.jpg',
      life: '10', encumbrance: ["12", "8", "10", "7", "8", "9"],
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [16, 5, 32, 21, 7] },

    { name: 'Zogar Sag', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ZogarSag.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ZogarSagSheet.jpg',
      life: '10', encumbrance: ["8", "6", "8", "6", "7", "7"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stretch Goal', skill_ids: [12, 21, 32, 33] },


    ##s
    # Khitai
    { name: 'Shentu', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Shentu.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ShentuSheet.jpg',
      life: '10', encumbrance: ["11", "7", "9", "6", "7", "8"],
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Khitai', skill_ids: [16, 30, 2] },

    # Nordheim
    { name: 'Niord', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Niord.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/NiordSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "8"],
      melee_dice: 'Orange', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Red',
      origin: 'Nordheim', skill_ids: [19, 16, 2, 21, 10] },

    # Stygia
    { name: 'Ikhmet', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Ikhmet.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/IkhmetSheet.jpg',
      life: '10', encumbrance: ["9", "6", "9", "6", "8", "8", "8"],
      melee_dice: 'Yellow-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Red', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Stygia', skill_ids: [2, 16, 5, 13] },


    ## Add-Ons
    # Brom Guest Box
    { name: 'Bêlit Queen of the Black Coast', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/BelitQueen.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BelitQueenSheet.jpg',
      life: '9', encumbrance: ["9", "7", "9", "6", "7", "8"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '5',
      defense_dice: 'Yellow',
      origin: 'Brom Guest Box', skill_ids: [13, 2, 16, 28, 6] },

    { name: 'Conan the Thief', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanThief.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanThiefSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "9", "11"],
      melee_dice: 'Red', melee_exertion: '6',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Brom Guest Box', skill_ids: [13, 16, 19, 11, 23] },


    # Paolo Parente Guest Box
    { name: 'Taramis', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Taramis.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/TaramisSheet.jpg',
      life: '9', encumbrance: ["9", "7", "8", "8", "8", "9"],
      melee_dice: 'Yellow', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '4',
      defense_dice: 'Yellow',
      origin: 'Paolo Parente Guest Box', skill_ids: [16, 33, 22, 28, 21] },

    { name: 'Valeria Warrior', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ValeriaWarrior.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ValeriaWarriorSheet.jpg',
      life: '10', encumbrance: ["10", "6", "8", "5", "5", "5", "6"],
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Paolo Parente Guest Box', skill_ids: [13, 2, 17, 7] },


    # Xavier Collette Guest Box
    { name: 'Bêlit the Princess', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/BelitPrincess.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BelitPrincessSheet.jpg',
      life: '9', encumbrance: ["9", "7", "9", "6", "7", "7", "8"],
      melee_dice: 'Orange', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Yellow',
      origin: 'Xavier Collette Guest Box', skill_ids: [13, 2, 17, 16, 28, 6] },

    { name: 'King Conan', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/KingConan.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/KingConanSheet.jpg',
      life: '11', encumbrance: ["11", "10", "11", "6", "8"],
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Xavier Collette Guest Box', skill_ids: [13, 16, 21, 28, 5] },


    # Vanir Valkyrie
    { name: 'Vanir Valkyrie', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/VanirValkyrie.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/VanirValkyrieSheet.jpg',
      life: '10', encumbrance: ["10", "7", "9", "7", "7", "8", "8", "9"],
      melee_dice: 'Orange-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '3',
      movement_free: '3', movement_exertion: '3',
      manipulation_dice: 'Red', manipulation_exersion: '2',
      defense_dice: 'Orange',
      origin: 'Vanir Valkyrie', skill_ids: [12, 2, 5, 16, 31] },


    # Yogah of Yag
    { name: 'Yogah of Yag', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/YogahYag.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/YogahofYagSheet.jpg',
      life: '12', encumbrance: ["13", "8", "10", "8", "8", "10", "10"],
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Yellow', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Yogah of Yag', skill_ids: [33, 22, 11, 29, 6] },


    # Conqueror
    { name: 'Baal-pteor', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/BaalPteor.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BaalPteorSheet.jpg',
      life: '11', encumbrance: ["12", "9", "11", "8", "10"],
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Orange', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Conan the Conqueror', skill_ids: [11, 3, 5, 31] },

    { name: 'Conan the Conqueror', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanConqueror.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanConquerorSheet.jpg',
      life: '12', encumbrance: ["12", "10", "11", "6", "8", "9"],
      melee_dice: 'Red', melee_exertion: '6',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Orange', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Conan the Conqueror', skill_ids: [13, 16, 19, 21, 28, 4] },

    { name: 'Conan the Pirate', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanPirate.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanPirateSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "9", "10"],
      melee_dice: 'Red', melee_exertion: '5',
      ranged_dice: 'Yellow-Reroll', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Conan the Conqueror', skill_ids: [13, 16, 19, 11, 21, 4] },

    { name: 'Gorm', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Gorm.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/GormSheet.jpg',
      life: '11', encumbrance: ["12", "8", "10", "6", "8", "8", "8", "10"],
      melee_dice: 'Red', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '4',
      defense_dice: 'Yellow-Reroll',
      origin: 'Conan the Conqueror', skill_ids: [13, 16, 2, 19, 11, 21] },

    { name: "N'Yaga", description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/NYaga.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/NYagaSheet.jpg',
      life: '10', encumbrance: ["8", "5", "7", "5", "5", "5", "5"],
      melee_dice: 'Yellow', melee_exertion: '4',
      ranged_dice: 'Yellow-Reroll', ranged_exertion: '3',
      movement_free: '2', movement_exertion: '2',
      manipulation_dice: 'Orange-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Conan the Conqueror', skill_ids: [16, 19, 22, 33] },

    { name: 'Nameless Horror', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/NamelessHorror.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/NamelessHorrorSheet.jpg',
      life: '11', encumbrance: ["13", "10", "12", "8", "8", "9", "10"],
      melee_dice: 'Red-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow', ranged_exertion: '0',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow', manipulation_exersion: '3',
      defense_dice: 'Red',
      origin: 'Conan the Conqueror', skill_ids: [18, 13, 3, 14, 1, 30, 25] },

    { name: 'Octavia', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Octavia.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/OctaviaSheet.jpg',
      life: '10', encumbrance: ["9", "7", "9", "5", "5", "6"],
      melee_dice: 'Yellow-Reroll', melee_exertion: '4',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '3',
      manipulation_dice: 'Orange-Reroll', manipulation_exersion: '3',
      defense_dice: 'Yellow-Reroll',
      origin: 'Conan the Conqueror', skill_ids: [2, 17, 23, 21, 28, 32] },

    { name: 'Winged One', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/WingedOne.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/WingedOneSheet.jpg',
      life: '11', encumbrance: ["12", "10", "12", "9", "9", "10"],
      melee_dice: 'Red-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow-Reroll', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '2',
      manipulation_dice: 'Orange-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange-Reroll',
      origin: 'Conan the Conqueror', skill_ids: [18, 10, 30, 4, 26, 20] },

    { name: 'Xaltotun', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Xaltotun.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/XaltotunSheet.jpg',
      life: '10', encumbrance: ["8", "6", "7", "5", "6"],
      melee_dice: 'Orange', melee_exertion: '3',
      ranged_dice: 'Orange', ranged_exertion: '4',
      movement_free: '2', movement_exertion: '4',
      manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '4',
      defense_dice: 'Orange',
      origin: 'Conan the Conqueror', skill_ids: [17, 22, 6, 33, 32, 21] },

    { name: 'Zenobia', description: '',
      quote: "",
      cite: "",
      hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Zenobia.jpg',
      hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ZenobiaSheet.jpg',
      life: '10', encumbrance: ["10", "6", "9", "5", "5", "6"],
      melee_dice: 'Yellow-Reroll', melee_exertion: '4',
      ranged_dice: 'Yellow-Reroll', ranged_exertion: '4',
      movement_free: '3', movement_exertion: '4',
      manipulation_dice: 'Orange-Reroll', manipulation_exersion: '3',
      defense_dice: 'Orange',
      origin: 'Conan the Conqueror', skill_ids: [12, 22, 16, 21, 28, 23, 27] },


     #The Shadow Kingdom
     { name: 'Brule', description: '',
       quote: "",
       cite: "",
       hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Brule.jpg',
       hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BruleSheet.jpg',
       life: '10', encumbrance: ["10", "7", "8", "5", "6", "7", "8", "8"],
       melee_dice: 'Orange-Reroll', melee_exertion: '4',
       ranged_dice: 'Red-Reroll', ranged_exertion: '2',
       movement_free: '3', movement_exertion: '4',
       manipulation_dice: 'Orange-Reroll', manipulation_exersion: '4',
       defense_dice: 'Orange',
       origin: 'The Shadow Kingdom', skill_ids: [12, 13, 19, 16, 22] },

     { name: 'King Kull', description: '',
       quote: "",
       cite: "",
       hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/KingKull.jpg',
       hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/KingKullSheet.jpg',
       life: '12', encumbrance: ["12", "8", "10", "6", "8", "9"],
       melee_dice: 'Orange-Reroll', melee_exertion: '5',
       ranged_dice: 'Orange', ranged_exertion: '4',
       movement_free: '2', movement_exertion: '4',
       manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '3',
       defense_dice: 'Orange',
       origin: 'The Shadow Kingdom', skill_ids: [13, 16, 19, 17, 21, 28, 5] },



      # Red Nails
      { name: 'Ageera', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Ageera.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/AgeeraSheet.jpg',
        life: '11', encumbrance: ["11", "8", "10", "6", "8", "8"],
        melee_dice: 'Red', melee_exertion: '5',
        ranged_dice: 'Yellow-Reroll', ranged_exertion: '4',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Orange', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [19, 30, 16, 11, 4] },                                        

      { name: 'Conan the Rogue', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanWanderer.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanRogueSheet.jpg',
        life: '10', encumbrance: ["11", "8", "10", "6", "7", "7", "7"],
        melee_dice: 'Orange', melee_exertion: '4',
        ranged_dice: 'Orange', ranged_exertion: '4',
        movement_free: '3', movement_exertion: '3',
        manipulation_dice: 'Red', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [17, 2, 16, 19, 22, 23] },  

      { name: 'Conan Free Companion', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanFreeComp.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanFreeCompSheet.jpg',
        life: '11', encumbrance: ["11", "8", "10", "6", "6", "8"],
        melee_dice: 'Red', melee_exertion: '5',
        ranged_dice: 'Orange', ranged_exertion: '4',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Orange', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [19, 13, 16, 11, 21, 4] },

      { name: 'Olmec', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Olmec.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/OlmecSheet.jpg',
        life: '11', encumbrance: ["11", "8", "10", "6", "8", "8"],
        melee_dice: 'Red', melee_exertion: '4',
        ranged_dice: 'Yellow-Reroll', ranged_exertion: '3',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Orange', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [19, 11, 16, 28, 21] },

      { name: 'Othryades', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Othryades.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/OthryadesSheet.jpg',
        life: '10', encumbrance: ["11", "8", "10", "7", "8", "8", "8", "9"],
        melee_dice: 'Red', melee_exertion: '4',
        ranged_dice: 'Orange', ranged_exertion: '5',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '4',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [16, 19, 9, 31, 7] },

      { name: 'Tascela', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Tascela.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/TascelaSheet.jpg',
        life: '10', encumbrance: ["9", "7", "9", "5", "7", "7"],
        melee_dice: 'Yellow-Reroll', melee_exertion: '4',
        ranged_dice: 'Yellow-Reroll', ranged_exertion: '4',
        movement_free: '3', movement_exertion: '3',
        manipulation_dice: 'Orange', manipulation_exersion: '4',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [22, 33, 32, 21] },

      { name: 'Techotl', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Techotl.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/TechotlSheet.jpg',
        life: '10', encumbrance: ["10", "6", "9", "6", "6", "8", "8"],
        melee_dice: 'Red', melee_exertion: '3',
        ranged_dice: 'Yellow-Reroll', ranged_exertion: '4',
        movement_free: '3', movement_exertion: '3',
        manipulation_dice: 'Red', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [17, 30, 16, 19, 21, 23] },

      { name: 'Tolkemec', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Tolkemec.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/TolkemecSheet.jpg',
        life: '9', encumbrance: ["8", "5", "7", "5", "6"],
        melee_dice: 'Yellow', melee_exertion: '4',
        ranged_dice: 'Yellow-Reroll', ranged_exertion: '3',
        movement_free: '2', movement_exertion: '2',
        manipulation_dice: 'Orange', manipulation_exersion: '4',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [19, 22, 33] },

      { name: 'Valeria Free Companion', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ValeriaFreeComp.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ValeriaFreeCompSheet.jpg',
        life: '10', encumbrance: ["10", "6", "8", "5", "5", "5", "6", "7", "9"],
        melee_dice: 'Orange-Reroll', melee_exertion: '4',
        ranged_dice: 'Yellow', ranged_exertion: '4',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Red Nails', skill_ids: [17, 13, 19, 16, 2, 7] },

      #Versus
      { name: 'Aja', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Aja.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/AjaSheet.jpg',
        life: '10', encumbrance: ["10", "8", "10", "6", "8", "8"],
        melee_dice: 'Orange', melee_exertion: '3',
        ranged_dice: 'Orange', ranged_exertion: '5',
        movement_free: '3', movement_exertion: '4',
        manipulation_dice: 'Orange', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Versus', skill_ids: [13, 2, 19, 7, 8] },   

      { name: 'Ganbaattar', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Ganbaattar.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/GanbaattarSheet.jpg',
        life: '10', encumbrance: ["12", "10", "12", "9", "9", "9"],
        melee_dice: 'Red', melee_exertion: '3',
        ranged_dice: 'Yellow', ranged_exertion: '3',
        movement_free: '2', movement_exertion: '3',
        manipulation_dice: 'Yellow', manipulation_exersion: '4',
        defense_dice: 'Red',
        origin: 'Versus', skill_ids: [30, 19, 16, 31, 11, 4] },  

      { name: 'Nestor', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Nestor.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/NestorSheet.jpg',
        life: '10', encumbrance: ["10", "6", "18", "6", "6", "6", "8"],
        melee_dice: 'Orange-Reroll', melee_exertion: '4',
        ranged_dice: 'Orange-Reroll', ranged_exertion: '3',
        movement_free: '3', movement_exertion: '3',
        manipulation_dice: 'Yellow', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Versus', skill_ids: [17, 13, 16, 9, 5] }, 


      #Worms of the Earth
     { name: 'Atla', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Atla.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/AtlaSheet.jpg',
        life: '11', encumbrance: ["8", "5", "7", "5", "5", "5"],
        melee_dice: 'Yellow', melee_exertion: '4',
        ranged_dice: 'Yellow', ranged_exertion: '3',
        movement_free: '2', movement_exertion: '2',
        manipulation_dice: 'Orange', manipulation_exersion: '3',
        defense_dice: 'Yellow-Reroll',
        origin: 'Worms of the Earth', skill_ids: [16, 22, 33] },  

      { name: 'Bran Mak Morn', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/BranMakMorn.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/BranMakMornSheet.jpg',
        life: '12', encumbrance: ["11", "8", "9", "6", "7", "8", "8"],
        melee_dice: 'Orange-Reroll', melee_exertion: '4',
        ranged_dice: 'Red', ranged_exertion: '2',
        movement_free: '3', movement_exertion: '3',
        manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Worms of the Earth', skill_ids: [13, 19, 2, 7, 16, 21, 28] },  

     { name: 'Grom', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Grom.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/GromSheet.jpg',
        life: '10', encumbrance: ["10", "8", "10", "6", "8", "8", "9", "11"],
        melee_dice: 'Red', melee_exertion: '5',
        ranged_dice: 'Orange', ranged_exertion: '3',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Orange', manipulation_exersion: '3',
        defense_dice: 'Orange',
        origin: 'Worms of the Earth', skill_ids: [13, 16, 30, 19, 11, 4] },  

     { name: 'Othna', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/Othna.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/OthnaSheet.jpg',
        life: '9', encumbrance: ["9", "6", "9", "7", "8", "8", "8", "8"],
        melee_dice: 'Yellow-Reroll', melee_exertion: '4',
        ranged_dice: 'Orange-Reroll', ranged_exertion: '4',
        movement_free: '3', movement_exertion: '2',
        manipulation_dice: 'Yellow-Reroll', manipulation_exersion: '4',
        defense_dice: 'Orange',
        origin: 'Worms of the Earth', skill_ids: [19, 16, 30, 9, 8] },  


      #Frazetta Guest Box
      { name: 'Conan the Berserker', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanBerserker.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanBerserkerSheet.jpg',
        life: '12', encumbrance: ["11", "8", "10", "6", "8"],
        melee_dice: 'Red-Reroll', melee_exertion: '5',
        ranged_dice: 'Yellow', ranged_exertion: '3',
        movement_free: '5', movement_exertion: '4',
        manipulation_dice: 'none', manipulation_exersion: '4',
        defense_dice: 'Orange',
        origin: 'Frazetta Guest Box', skill_ids: [12, 16, 1, 21, 4] },  

      { name: 'Conan the Destroyer', description: '',
        quote: "",
        cite: "",
        hero_image: 'https://drabelpdx.s3.us-west-2.amazonaws.com/Conan/figures/ConanDestroyer.jpg',
        hero_sheet: 'https://drabelpdx.s3-us-west-2.amazonaws.com/Conan/heroes/ConanDestroyerSheet.jpg',
        life: '12', encumbrance: ["11", "8", "10", "6", "8", "8"],
        melee_dice: 'Red', melee_exertion: '5',
        ranged_dice: 'Orange', ranged_exertion: '3',
        movement_free: '2', movement_exertion: '4',
        manipulation_dice: 'Orange', manipulation_exersion: '4',
        defense_dice: 'Orange',
        origin: 'Frazetta Guest Box', skill_ids: [13, 16, 19, 21, 4] }, 

  ])
