# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
# mnmnmnm
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

tiles = Tile.create([
  { name: 'Event', description: '',
    role: 'Event', move: '–', armor: '–',
    melee_dice: '–', ranged_dice: '–',
    origin: 'Core Game', count: '3', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event1.png',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event1.png',
    token_image: '' },

  { name: 'Captain', description: '',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [28, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Captain.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Captain.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CaptainToken.png' },

  { name: 'Skuthus', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [32, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skuthus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skuthus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkuthusToken.png' },

  { name: 'Zogar Sag', description: 'Pict Shaman',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: '2 Orange-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZogarSag.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZogarSag.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZogarSagToken.png' },

  { name: 'Zaporavo', description: '',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [16, 28],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Zaporavo.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zaporavo.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZaporavoToken.png' },

  { name: 'Akivasha', description: 'Stygian Priestess turned Vampire',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [6, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Akivasha.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Akivasha.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AkivashaToken.png' },

  { name: 'Constantius', description: 'The Falcon',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [7, 28],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Constantius.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Constantius.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ConstantiusToken.png' },

  { name: 'Hyperborean Primitive', description: '',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: '2 Orange, Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [26, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/HyperboreanPrimitive.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HyperboreanPrimitive.png' ,
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HyperboreanPrimitiveToken.png' },

  { name: 'Khemsa', description: 'A Black Circle Adept',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Khemsa.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Khemsa.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhemsaToken.png' },

  { name: 'Natohk', description: 'Stygian Sorceror Thugra Khotan',
    role: 'Leader', move: '3', armor: '2',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Natohk.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Natohk.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/NatohkToken.png' },

  { name: 'Warlock', description: '',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [32, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Warlock.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Warlock.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/WarlockToken.png' },

  { name: 'Gitara', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee_dice: '3 Yellow-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [17, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Gitara.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Gitara.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GitaraToken.png' },

  { name: 'Thalis', description: '',
    role: 'Leader', move: '3', armor: '2',
    melee_dice: 'Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [24, 28],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Princess.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thalis.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThalisToken.png' },

  { name: 'Ageera', description: 'Witch Hunter Finder',
    role: 'Leader', move: '3', armor: '2',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [16, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Ageera.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Ageera.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AgeeraToken.png' },

  { name: 'Shubba', description: 'Witch Hunter Sorcerer',
    role: 'Leader', move: '2', armor: '1',
    melee_dice: '2 Yellow', ranged_dice: '–',
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shubba.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shubba.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShubbaToken.png' },

  { name: 'Afari', description: 'Witch Hunter Warlord',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [5, 7],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Afari.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Afari.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AfariToken.png' },

  { name: 'Ghayoor', description: 'Witch Hunter Bodyguard',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [5, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Ghayoor.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Ghayoor.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GhayoorToken.png' },

  { name: 'Shafiah', description: 'Witch Hunter Bodyguard',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [5, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shafiah.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shafiah.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShafiahToken.png' },

  { name: 'Dark Demon', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: '3 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [10, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/DarkDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DarkDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DarkDemonToken.png' },

  { name: 'Giant Snake', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: '3 Orange-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [10, 11],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantSnake.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSnake.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSnakeToken.png' },

  { name: 'Khosatral Khel', description: '',
    role: 'Monster', move: '3', armor: '12',
    melee_dice: '3 Red', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [4, 11],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KhosatralKhel.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Khosatral+Khel.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhosatralKhelToken.png' },

  { name: 'Outer Dark Demon', description: '',
    role: 'Monster', move: '8', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [12, 18],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/OuterDarkDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Outer+Dark+Demon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/OuterDarkDemonToken.png' },

  { name: 'Thak', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thak.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thak.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThakToken.png' },

  { name: 'Gray Man-Ape', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: 'Red, 2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [10, 19],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GrayManApe.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Gray+Man-Ape.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GrayManApeToken.png' },

  { name: 'Bone Golem', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee_dice: '3 Red', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [11, 25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BoneGolem.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BoneGolem.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BoneGolemToken.png' },

  { name: 'Swamp Demon', description: '',
    role: 'Monster', move: '2', armor: '2',
    melee_dice: '2 Red-Reroll, Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [25, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/SwampDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SwampDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SwampDemonToken.png' },

  { name: 'Forest Demon', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee_dice: '3 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [5, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ForestDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ForestDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ForestDemonToken.png' },

  { name: 'Giant Scorpion', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee_dice: '3 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [27],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantScorpion.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantScorpion.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantScorpionToken.png' },

  { name: 'Giant Spider', description: '',
    role: 'Monster', move: '4', armor: '2',
    melee_dice: 'Red-Reroll, 2 Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [15, 19],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantSpider.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSpider.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSpiderToken.png' },

  { name: 'Thog', description: '',
    role: 'Monster', move: '1', armor: '3',
    melee_dice: '3 Red-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '2', skill_ids: [14, 25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thog.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thog.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThogToken.png' },

  { name: 'Thog Elite', description: '',
    role: 'Monster', move: '1', armor: '3',
    melee_dice: '3 Red-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '2', skill_ids: [3, 25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thog.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thog2.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThogToken.png' },

  { name: 'Thaug', description: '',
    role: 'Monster', move: '0', armor: '8',
    melee_dice: '4 Red-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [25, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thaug.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thaug.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThaugToken.png' },

  { name: 'Pirates', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates.png',
    token_image: '' },

  { name: 'Pirates - Elite', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: '2 Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesElite.png',
    token_image: '' },

  { name: 'Pirates - Green', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesGreen.png',
    token_image: '' },

  { name: 'Pirates - Blue', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesBlue.png',
    token_image: '' },

  { name: 'Pirates - Red', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesRed.png',
    token_image: '' },

  { name: 'Pirates - Orange', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesOrange.png',
    token_image: '' },

  { name: 'Pirates - Orange Elite', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: '2 Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Orange2.png',
    token_image: '' },

  { name: 'Pirates - Purple', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Purple.png',
    token_image: '' },

  { name: 'Hyenas', description: '',
    role: 'Minion', move: '5', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [12, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Hyenas.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hyenas.png',
    token_image: '' },

  { name: 'Pict Hunters', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHunters.png',
    token_image: '' },

  { name: 'Pict Hunters - Green', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersGreen.png',
    token_image: '' },

  { name: 'Pict Hunters - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersBlue.png',
    token_image: '' },

  { name: 'Pict Hunters - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersRed.png',
    token_image: '' },

  { name: 'Pict Hunters - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersOrange.png',
    token_image: '' },

  { name: 'Pict Warriors', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: 'Red-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [10, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Warriors+-+neutral.png',
    token_image: '' },

  { name: 'Pict Warriors - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: 'Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [10, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictWarriorsPurple.png',
    token_image: '' },

  { name: 'Pict Archers', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Yellow, Yellow-Reroll',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Archers+-+neutral.png',
    token_image: '' },

  { name: 'Pict Archers - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Yellow, Yellow-Reroll',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictArchersOrange.png',
    token_image: '' },

  { name: 'Bossonian Guards', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuards.png',
    token_image: '' },

  { name: 'Bossonian Guards - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsGreen.png',
    token_image: '' },

  { name: 'Bossonian Guards - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsBlue.png',
    token_image: '' },

  { name: 'Bossonian Guards - Red', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsRed.png',
    token_image: '' },

  { name: 'Bossonian Guards - Orange', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsOrange.png',
    token_image: '' },

  { name: 'Bossonian Guards - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+Purple.png',
    token_image: '' },

  { name: 'Bossonian Archers', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '–', ranged_dice: '2 Yellow-Reroll',
    origin: 'Core Game', count: '1', skill_ids: [8],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianArchers.png',
    token_image: '' },

  { name: 'Bossonian Archers - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '–', ranged_dice: '2 Yellow-Reroll',
    origin: 'Core Game', count: '1', skill_ids: [8],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianArchersPurple.png',
    token_image: '' },

  { name: 'Crossbowmen', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Red',
    origin: 'Crossbowmen', count: '1', skill_ids: [8, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crossbowmen.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crossbowmen.png',
    token_image: '' },

  { name: 'Crossbowmen - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Red',
    origin: 'Crossbowmen', count: '1', skill_ids: [8, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crossbowmen.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CrossbowmenRed.png',
    token_image: '' },

  { name: 'Crossbowmen - Green', description: 'An elite troop of sharpshooters',
    role: 'Minion', move: '2', armor: '0', cost: '3',
    melee_dice: '–', ranged_dice: 'Red-Reroll',
    origin: 'Crossbowmen', count: '1', skill_ids: [8, 9],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crossbowmen.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CrossbowmenGreen.png',
    token_image: '' },

  { name: 'Skeletons', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons.png',
    token_image: '' },

  { name: 'Skeletons - Green', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Green.png',
    token_image: '' },

  { name: 'Skeletons - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Blue.png',
    token_image: '' },

  { name: 'Skeletons - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsRed.png',
    token_image: '' },

  { name: 'Skeletons - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsOrange.png',
    token_image: '' },

  { name: 'Skeletons - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsPurple.png',
    token_image: '' },

  { name: 'Skeletons - Elite', description: '',
    role: 'Minion', move: '2', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+neutral2.png',
    token_image: '' },

  { name: 'Skeletons - Red Elite', description: '',
    role: 'Minion', move: '2', armor: '0', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsRedElite.png',
    token_image: '' },

  { name: 'Mummies', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies.png',
    token_image: '' },

  { name: 'Mummies - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesGreen.png',
    token_image: '' },

  { name: 'Mummies - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesBlue.png',
    token_image: '' },

  { name: 'Mummies - Orange', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Orange.png',
    token_image: '' },

  { name: 'Mummies - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesPurple.png',
    token_image: '' },

  { name: 'Mummies - Elite', description: '',
    role: 'Minion', move: '2', armor: '3', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+neutral2.png',
    token_image: '' },

  { name: 'Mummies - Blue Elite', description: '',
    role: 'Minion', move: '2', armor: '3', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Blue2.png',
    token_image: '' },

  { name: 'Tentacles', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+neutral.png',
    token_image: '' },

  { name: 'Tentacles - Blue', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+Blue.png',
    token_image: '' },

  { name: 'Tentacles - Red', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+Red.png',
    token_image: '' },

  { name: 'Tentacles - Orange', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+Orange.png',
    token_image: '' },

  { name: "Amboola", description: 'A Kushite Commander',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: '2 Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [5, 28,],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Amboola.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Amboola.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AmboolaToken.png' },

  { name: "Balthus", description: 'A scout and a deadeye shot',
    role: 'Hero', move: '3', armor: '1',
    melee_dice: '–', ranged_dice: 'Red-Reroll, Orange-Reroll',
    origin: 'Stretch Goals', count: '1', skill_ids: [8, 9],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Balthus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Balthus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BalthusToken.png' },

  { name: "Bêlit", description: 'Queen of the Black Coast',
    role: 'Hero', move: '3', armor: '1',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [6, 32],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Belit.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Belit.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BelitToken.png' },

  { name: "Conan", description: '',
    role: 'Hero', move: '3', armor: '3',
    melee_dice: '3 Red', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [4, 11],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Conan.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Conan.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ConanToken.png' },

  { name: "Hadrathus", description: '',
    role: 'Hero', move: '2', armor: '2',
    melee_dice: '–', ranged_dice: '2 Yellow',
    origin: 'Stretch Goals', count: '1', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Hadrathus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hadrathus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HadrathusToken.png' },

  { name: "Kerim Shah", description: 'A Turanian Prince',
    role: 'Hero', move: '2', armor: '2',
    melee_dice: '–', ranged_dice: '2 Orange',
    origin: 'Stretch Goals', count: '1', skill_ids: [9, 32],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KerimShah.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Kerim+Shah.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KerimShahToken.png' },

  { name: "N'Gora", description: '',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: '–', ranged_dice: '2 Red',
    origin: 'Stretch Goals', count: '1', skill_ids: [8, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/NGora.jpg',
    tile_image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/N'Gora.png",
    token_image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/N'GoraToken.png" },

  { name: "Olgerd Vladislav", description: 'The Tiger',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [4, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/OlgerdVladislav.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Olgerd+Vladislav.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/OlgerdVladislavToken.png' },

  { name: "Pallantides", description: 'Captain of the Black Dragons',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: 'Red-Reroll, Red', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [28, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pallantides.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pallantides.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PallantidesToken.png' },

  { name: "Shevatas", description: '',
    role: 'Hero', move: '3', armor: '2',
    melee_dice: '–', ranged_dice: '2 Orange',
    origin: 'Stretch Goals', count: '1', skill_ids: [12, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shevatas.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shevatas.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShevatasToken.png' },

  { name: "Taurus", description: 'Prince of Thieves',
    role: 'Hero', move: '3', armor: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [5, 12],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Taurus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Taurus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/TaurusToken.png' },

  { name: "Valeria", description: '',
    role: 'Hero', move: '3', armor: '2',
    melee_dice: '2 Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [7, 17],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Valeria.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Valeria.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ValeriaToken.png' },

  { name: "Zelata", description: '',
    role: 'Hero', move: '2', armor: '1',
    melee_dice: 'Yellow-Reroll, Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [28, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Zelata.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zelata.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZelataToken.png' },

  { name: "Bêlit's Guards", description: '',
    role: 'Ally', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BelitGuards.jpg',
    tile_image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Belit's+Guards.png",
    token_image: '' },

  { name: "Vanir Valkyrie", description: 'Not Red Sonja',
    role: 'Hero', move: '3', armor: '3',
    melee_dice: '3 Orange-Reroll', ranged_dice: '–',
    origin: 'Vanir Valkyrie', count: '2', skill_ids: [5, 12],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirValkyrie.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Valkyrie.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirValkyrieToken.png' },

  { name: "Black Dragons", description: "King Conan's personal bodyguard",
    role: 'Ally', move: '2', armor: '2',
    melee_dice: 'Red-Reroll', ranged_dice: '–',
    origin: 'Black Dragons', count: '1', skill_ids: [7, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BlackDragons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Black+Dragons.png',
    token_image: '' },

  { name: "Camel", description: 'Punch a camel',
    role: 'Ally', move: '4', armor: '2',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Camel.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Camel.png',
    token_image: '' },

  { name: "Conan's Lion", description: '',
    role: 'Ally', move: '4', armor: '3', cost: '4',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [16, 17],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AmaraLion.jpg',
    tile_image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Conan's+Lion.png",
    token_image: '' },

  { name: "Kothian Archer", description: '',
    role: 'Ally', move: '3', armor: '2',
    melee_dice: '–', ranged_dice: 'Red',
    origin: 'Stretch Goals', count: '1', skill_ids: [8, 9],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KothianArcher.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Kothian+Archer.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KothianArcherToken.png' },

  { name: "Slasher", description: "Balthus' dog and ally",
    role: 'Ally', move: '5', armor: '3',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [12, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Slasher.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Slasher.png',
    token_image: '' },

  { name: "Princess", description: '',
    role: 'Ally', move: '2', armor: '0',
    melee_dice: '–', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Princess.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Princess.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PrincessToken.png' },

  { name: "Atali", description: "The Frost-Giant's Daughter",
    role: 'Leader', move: '3', armor: '0',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '3', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Atali.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Atali.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AtaliToken.png' },

  { name: "Yazdigerd", description: '',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '2', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skuthus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Yazdigerd.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkuthusToken.png' },

  { name: "Nijgor", description: "Atali's Brother",
    role: 'Monster', move: '3', armor: '1',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '2', skill_ids: [25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Nijgor.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Nijgor.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/NijgorToken.png' },

  { name: "Seski", description: "Atali's Brother",
    role: 'Monster', move: '2', armor: '2',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '2', skill_ids: [25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Seski.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Seski.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SeskiToken.png' },

  { name: "Vanir Warriors", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Warriors+-+neutral.png',
    token_image: '' },

  { name: "Vanir Warriors - Blue", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [5],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Warriors+-+Blue.png',
    token_image: '' },

  { name: "Vanir Warriors - Purple", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [5],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Warriors+-+Purple.png',
    token_image: '' },

  { name: "Vanir Zombies - Green", description: '',
    role: 'Minion', move: '1', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Zombies+-+Green.png',
    token_image: '' },

  { name: "Vanir Zombies - Red", description: '',
    role: 'Minion', move: '1', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Zombies+-+Red.png',
    token_image: '' },

  { name: "Vanir Primitives", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunter.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Primitives+-+neutral.png',
    token_image: '' },

  { name: "Vanir Primitives - Red", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Primitives+-+Red.png',
    token_image: '' },

  { name: "Crows", description: '',
    role: 'Minion', move: '5', armor: '1', cost: '1',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [18, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crows.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crows+-+neutral.png',
    token_image: '' },

  { name: "Crows - Red", description: '',
    role: 'Minion', move: '5', armor: '1', cost: '1',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [18, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crows.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crows+-+Red.png',
    token_image: '' },

  { name: "Wolves", description: '',
    role: 'Minion', move: '5', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [12, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZelataWolf.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Wolves+-+neutral.png',
    token_image: '' },

  { name: "Aesir Zombies - Purple", description: '',
    role: 'Minion', move: '2', armor: '2', cost: '3',
    melee_dice: 'Red', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [7, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AesirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Aesir+Zombies+-+Purple.png',
    token_image: '' },

  { name: "Aesir Warriors", description: '',
    role: 'Ally', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AesirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Aesir+Warriors+-+neutral.png',
    token_image: '' },

  { name: "Aesir Warriors - Red", description: '',
    role: 'Ally', move: '2', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [12],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AesirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Aesir+Warriors+-+Red.png',
    token_image: '' }
])
