# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
# mnmnmnm
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

tiles = Tile.create([
  { name: 'Captain', description: '',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [28, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Captain.png' },
  { name: 'Skuthus', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [32, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skuthus.png' },
  { name: 'Zogar Sag', description: 'Pict Shaman',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: '2 Orange-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zogar+Sag.png' },
  { name: 'Zaporavo', description: '',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [16, 28],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zaporavo.png' },
  { name: 'Akivasha', description: 'Stygian Priestess turned Vampire',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [6, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Akivasha.png' },
  { name: 'Constantius', description: 'The Falcon',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [7, 28],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Constantius.png' },
  { name: 'Hyperborean Primitive', description: '',
    role: 'Leader', move: '3', armor: '3',
    melee_dice: '2 Orange, Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [26, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hyperborean+Primitive.png' },
  { name: 'Khemsa', description: 'A Black Circle Adept',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [22, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Khemsa.png' },
  { name: 'Natohk', description: 'Stygian Sorceror Thugra Khotan',
    role: 'Leader', move: '3', armor: '2',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [22, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Natohk.png' },
  { name: 'Warlock', description: '',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [32, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Warlock.png' },
  { name: 'Gitara', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee_dice: '3 Yellow-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [17, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Gitara.png' },
  { name: 'Thalis', description: '',
    role: 'Leader', move: '3', armor: '2',
    melee_dice: 'Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [24, 28],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thalis.png' },
  { name: 'Ageera', description: 'Witch Hunter Finder',
    role: 'Leader', move: '3', armor: '2',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [16, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Ageera.png' },
  { name: 'Shubba', description: 'Witch Hunter Sorcerer',
    role: 'Leader', move: '2', armor: '1',
    melee_dice: '2 Yellow', ranged_dice: '–',
    origin: 'Add On', count: '1', skill_ids: [22, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shubba.png' },
  { name: 'Afari', description: 'Witch Hunter Warlord',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'Add On', count: '1', skill_ids: [5, 7],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Afari.png' },
  { name: 'Ghayoor', description: 'Witch Hunter Bodyguard',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Add On', count: '1', skill_ids: [5, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Ghayoor.png' },
  { name: 'Shafiah', description: 'Witch Hunter Bodyguard',
    role: 'Leader', move: '2', armor: '3',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Add On', count: '1', skill_ids: [5, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shafiah.png' },
  { name: 'Dark Demon', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: '3 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [10, 26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Dark+Demon.png' },
  { name: 'Giant Snake', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: '3 Orange-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [10, 11],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Giant+Snake.png' },
  { name: 'Khosatral Khel', description: '',
    role: 'Monster', move: '3', armor: '12',
    melee_dice: '3 Red', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [4, 11],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Khosatral+Khel.png' },
  { name: 'Outer Dark Demon', description: '',
    role: 'Monster', move: '8', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [12, 18],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Outer+Dark+Demon.png' },
  { name: 'Thak', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [10],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thak.png' },
  { name: 'Gray Man-Ape', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee_dice: 'Red, 2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [10, 19],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Gray+Man-Ape.png' },
  { name: 'Bone Golem', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee_dice: '3 Red', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [11, 25],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bone+Golem.png' },
  { name: 'Swamp Demon', description: '',
    role: 'Monster', move: '2', armor: '2',
    melee_dice: '2 Red-Reroll, Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [25, 26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Swamp+Demon.png' },
  { name: 'Forest Demon', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee_dice: '3 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [5, 10],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Forest+Demon.png' },
  { name: 'Giant Scorpion', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee_dice: '3 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [27],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Giant+Scorpion.png' },
  { name: 'Giant Spider', description: '',
    role: 'Monster', move: '4', armor: '2',
    melee_dice: 'Red-Reroll, 2 Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [15, 19],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Giant+Spider.png' },
  { name: 'Thog', description: '',
    role: 'Monster', move: '1', armor: '3',
    melee_dice: '3 Red-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '2', skill_ids: [14, 25],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thog.png' },
  { name: 'Thog2', description: '',
    role: 'Monster', move: '1', armor: '3',
    melee_dice: '3 Red-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '2', skill_ids: [3, 25],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thog2.png' },
  { name: 'Thaug', description: '',
    role: 'Monster', move: '0', armor: '8',
    melee_dice: '4 Red-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [25, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thaug.png' },
  { name: 'Pirates - neutral', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+neutral.png' },
  { name: 'Pirates - neutral2', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: '2 Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+neutral2.png' },
  { name: 'Pirates - Green', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Green.png' },
  { name: 'Pirates - Blue', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Blue.png' },
  { name: 'Pirates - Red', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Red.png' },
  { name: 'Pirates - Orange', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Orange.png' },
  { name: 'Pirates - Orange2', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: '2 Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Orange2.png' },
  { name: 'Pirates - Purple', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates+-+Purple.png' },
  { name: 'Hyenas - neutral', description: '',
    role: 'Minion', move: '5', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Core Game', count: '2', skill_ids: [12, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hyenas+-+neutral.png' },
  { name: 'Pict Hunters - neutral', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Hunters+-+neutral.png' },
  { name: 'Pict Hunters - Green', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Hunters+-+Green.png' },
  { name: 'Pict Hunters - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Hunters+-+Blue.png' },
  { name: 'Pict Hunters - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Hunters+-+Red.png' },
  { name: 'Pict Hunters - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Hunters+-+Orange.png' },
  { name: 'Pict Warriors - neutral', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: 'Red-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [10, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Warriors+-+neutral.png' },
  { name: 'Pict Warriors - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: 'Red-Reroll', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [10, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Warriors+-+Purple.png' },
  { name: 'Pict Archers - neutral', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Yellow, Yellow-Reroll',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Archers+-+neutral.png' },
  { name: 'Pict Archers - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Yellow, Yellow-Reroll',
    origin: 'Stretch Goals', count: '1', skill_ids: [16, 30],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pict+Archers+-+Orange.png' },
  { name: 'Bossonian Guards - neutral', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+neutral.png' },
  { name: 'Bossonian Guards - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+Green.png' },
  { name: 'Bossonian Guards - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+Blue.png' },
  { name: 'Bossonian Guards - Red', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+Red.png' },
  { name: 'Bossonian Guards - Orange', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+Orange.png' },
  { name: 'Bossonian Guards - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Guards+-+Purple.png' },
  { name: 'Bossonian Archers - neutral', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '–', ranged_dice: '2 Yellow-Reroll',
    origin: 'Core Game', count: '1', skill_ids: [8],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Archers+-+neutral.png' },
  { name: 'Bossonian Archers - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '–', ranged_dice: '2 Yellow-Reroll',
    origin: 'Core Game', count: '1', skill_ids: [8],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Bossonian+Archers+-+Purple.png' },
  { name: 'Crossbowmen - neutral', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Red',
    origin: 'Add On', count: '1', skill_ids: [8, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crossbowmen+-+neutral.png' },
  { name: 'Crossbowmen - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee_dice: '–', ranged_dice: 'Red',
    origin: 'Add On', count: '1', skill_ids: [8, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crossbowmen+-+Red.png' },
  { name: 'Crossbowmen - Green', description: 'An elite troop of sharpshooters',
    role: 'Minion', move: '2', armor: '0', cost: '3',
    melee_dice: '–', ranged_dice: 'Red-Reroll',
    origin: 'Add On', count: '1', skill_ids: [8, 9],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crossbowmen+-+Green.png' },
  { name: 'Skeletons - neutral', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+neutral.png' },
  { name: 'Skeletons - Green', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Green.png' },
  { name: 'Skeletons - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Blue.png' },
  { name: 'Skeletons - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Red.png' },
  { name: 'Skeletons - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Orange.png' },
  { name: 'Skeletons - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Purple.png' },
  { name: 'Skeletons - neutral2', description: '',
    role: 'Minion', move: '2', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+neutral2.png' },
  { name: 'Skeletons - Red2', description: '',
    role: 'Minion', move: '2', armor: '0', cost: '1',
    melee_dice: 'Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons+-+Red2.png' },
  { name: 'Mummies - neutral', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+neutral.png' },
  { name: 'Mummies - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Green.png' },
  { name: 'Mummies - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Blue.png' },
  { name: 'Mummies - Orange', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Orange.png' },
  { name: 'Mummies - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Purple.png' },
  { name: 'Mummies - neutral2', description: '',
    role: 'Minion', move: '2', armor: '3', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+neutral2.png' },
  { name: 'Mummies - Blue2', description: '',
    role: 'Minion', move: '2', armor: '3', cost: '2',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies+-+Blue2.png' },
  { name: 'Tentacles - neutral', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+neutral.png' },
  { name: 'Tentacles - Blue', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+Blue.png' },
  { name: 'Tentacles - Red', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+Red.png' },
  { name: 'Tentacles - Orange', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [1, 3],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles+-+Orange.png' },
  { name: "Amboola", description: 'A Kushite Commander',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: '2 Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [5, 28,],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Amboola.png' },
  { name: "Balthus", description: 'A scout and a deadeye shot',
    role: 'Hero', move: '3', armor: '1',
    melee_dice: '–', ranged_dice: 'Red-Reroll, Orange-Reroll',
    origin: 'Stretch Goals', count: '1', skill_ids: [8, 9],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Balthus.png' },
  { name: "Belit", description: 'Queen of the Black Coast',
    role: 'Hero', move: '3', armor: '1',
    melee_dice: '2 Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [6, 32],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Belit.png' },
  { name: "Conan", description: '',
    role: 'Hero', move: '3', armor: '3',
    melee_dice: '3 Red', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [4, 11],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Conan.png' },
  { name: "Hadrathus", description: '',
    role: 'Hero', move: '2', armor: '2',
    melee_dice: '–', ranged_dice: '2 Yellow',
    origin: 'Stretch Goals', count: '1', skill_ids: [22, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hadrathus.png' },
  { name: "Kerim Shah", description: 'A Turanian Prince',
    role: 'Hero', move: '2', armor: '2',
    melee_dice: '–', ranged_dice: '2 Orange',
    origin: 'Stretch Goals', count: '1', skill_ids: [9, 32],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Kerim+Shah.png' },
  { name: "N'Gora", description: '',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: '–', ranged_dice: '2 Red',
    origin: 'Stretch Goals', count: '1', skill_ids: [8, 29],
    image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/N'Gora.png" },
  { name: "Olgerd Vladislav", description: 'The Tiger',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: '2 Red-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [4, 10],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Olgerd+Vladislav.png' },
  { name: "Pallantides", description: 'Captain of the Black Dragons',
    role: 'Hero', move: '2', armor: '3',
    melee_dice: 'Red-Reroll, Red', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [28, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pallantides.png' },
  { name: "Shevatas", description: '',
    role: 'Hero', move: '3', armor: '2',
    melee_dice: '–', ranged_dice: '2 Orange',
    origin: 'Stretch Goals', count: '1', skill_ids: [12, 30],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shevatas.png' },
  { name: "Taurus", description: 'Prince of Thieves',
    role: 'Hero', move: '3', armor: '2',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [5, 12],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Taurus.png' },
  { name: "Valeria", description: '',
    role: 'Hero', move: '3', armor: '2',
    melee_dice: '2 Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [7, 17],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Valeria.png' },
  { name: "Zelata", description: '',
    role: 'Hero', move: '2', armor: '1',
    melee_dice: 'Yellow-Reroll, Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [28, 33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zelata.png' },
  { name: "Belit's Guards", description: '',
    role: 'Ally', move: '3', armor: '1', cost: '1',
    melee_dice: 'Orange-Reroll, Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [16, 29],
    image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Belit's+Guards.png" },
  { name: "Vanir Valkyrie", description: 'Not Red Sonja',
    role: 'Hero', move: '3', armor: '3',
    melee_dice: '3 Orange-Reroll', ranged_dice: '–',
    origin: 'Stretch Goals', count: '2', skill_ids: [5, 12],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Valkyrie.png' },
  { name: "Black Dragons", description: "King Conan's personal bodyguard",
    role: 'Ally', move: '2', armor: '2',
    melee_dice: 'Red-Reroll', ranged_dice: '–',
    origin: 'Add On', count: '1', skill_ids: [7, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Black+Dragons.png' },
  { name: "Camel", description: 'Punch a camel',
    role: 'Ally', move: '4', armor: '2',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Camel.png' },
  { name: "Conan's Lion", description: '',
    role: 'Ally', move: '4', armor: '3', cost: '4',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'King Pledge', count: '1', skill_ids: [16, 17],
    image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Conan's+Lion.png" },
  { name: "Kothian Archer", description: '',
    role: 'Ally', move: '3', armor: '2',
    melee_dice: '–', ranged_dice: 'Red',
    origin: 'Stretch Goals', count: '1', skill_ids: [8, 9],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Kothian+Archer.png' },
  { name: "Slasher", description: "Balthus' dog and ally",
    role: 'Ally', move: '5', armor: '3',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Stretch Goals', count: '1', skill_ids: [12, 29],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Slasher.png' },
  { name: "Princess", description: '',
    role: 'Ally', move: '2', armor: '0',
    melee_dice: 'Red, Orange', ranged_dice: '–',
    origin: 'Core Game', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Princess.png' },
  { name: "Atali", description: "The Frost-Giant's Daughter",
    role: 'Leader', move: '3', armor: '0',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '3', skill_ids: [33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Atali.png' },
  { name: "Yazdigerd", description: '',
    role: 'Leader', move: '2', armor: '2',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '2', skill_ids: [33],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Yazdigerd.png' },
  { name: "Nijgor", description: "Atali's Brother",
    role: 'Monster', move: '3', armor: '1',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '2', skill_ids: [25],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Nijgor.png' },
  { name: "Seski", description: "Atali's Brother",
    role: 'Monster', move: '2', armor: '2',
    melee_dice: '2 Red', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '2', skill_ids: [25],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Seski.png' },
  { name: "Vanir Warriors - neutral", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Warriors+-+neutral.png' },
  { name: "Vanir Warriors - Blue", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [5],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Warriors+-+Blue.png' },
  { name: "Vanir Warriors - Purple", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: '2 Yellow-Reroll', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [5],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Warriors+-+Purple.png' },
  { name: "Vanir Zombies - Green", description: '',
    role: 'Minion', move: '1', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [3],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Zombies+-+Green.png' },
  { name: "Vanir Zombies - Red", description: '',
    role: 'Minion', move: '1', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [3],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Zombies+-+Red.png' },
  { name: "Vanir Primitives - neutral", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Primitives+-+neutral.png' },
  { name: "Vanir Primitives - Red", description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Vanir+Primitives+-+Red.png' },
  { name: "Crows - neutral", description: '',
    role: 'Minion', move: '5', armor: '1', cost: '1',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [18, 26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crows+-+neutral.png' },
  { name: "Crows - Red", description: '',
    role: 'Minion', move: '5', armor: '1', cost: '1',
    melee_dice: 'Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [18, 26],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crows+-+Red.png' },
  { name: "Wolves - neutral", description: '',
    role: 'Minion', move: '5', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [12, 16],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Wolves+-+neutral.png' },
  { name: "Aesir Zombies - Purple", description: '',
    role: 'Minion', move: '2', armor: '2', cost: '3',
    melee_dice: 'Red', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [7, 10],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Aesir+Zombies+-+Purple.png' },
  { name: "Aesir Warriors - neutral", description: '',
    role: 'Ally', move: '2', armor: '2', cost: '1',
    melee_dice: 'Orange, Yellow', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Aesir+Warriors+-+neutral.png' },
  { name: "Aesir Warriors - Red", description: '',
    role: 'Ally', move: '2', armor: '0', cost: '1',
    melee_dice: 'Orange', ranged_dice: '–',
    origin: 'Nordheim Expansion', count: '1', skill_ids: [12],
    image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Aesir+Warriors+-+Red.png' },
])
