# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
# mnmnmnm
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Tile.create!([

  ## Core Game Tiles
  #  Event Tiles
  { name: 'Event 1', description: '',
    role: 'Event', move: '–', armor: '–',
    melee: '–', ranged: '–', bone_ids: [],
    origin: 'Core Game', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event1.png',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event1.png',
    token_image: '' },

  { name: 'Event 2', description: '',
    role: 'Event', move: '–', armor: '–',
    melee: '–', ranged: '–', bone_ids: [],
    origin: 'Core Game', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event2.png',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event2.png',
    token_image: '' },

  # Leader Tiles
  { name: 'Captain', description: '',
    role: 'Leader', move: '3', armor: '3',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Core Game', count: '2', skill_ids: [28, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Captain.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Captain.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CaptainToken.png' },

  { name: 'Skuthus', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Core Game', count: '2', skill_ids: [32, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skuthus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skuthus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkuthusToken.png' },

  { name: 'Thalis', description: '',
    role: 'Leader', move: '3', armor: '2',
    melee: 'Yellow-Reroll', ranged: '–', bone_ids: [6],
    origin: 'Core Game', count: '1', skill_ids: [24, 28],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Princess.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thalis.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThalisToken.png' },

  { name: 'Zogar Sag', description: 'Pict Shaman',
    role: 'Leader', move: '3', armor: '3',
    melee: '2 Orange-Reroll', ranged: '–', bone_ids: [4, 4],
    origin: 'Core Game', count: '2', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZogarSag.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZogarSag.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZogarSagToken.png' },

  { name: 'Zaporavo', description: '',
    role: 'Leader', move: '2', armor: '3',
    melee: '2 Red-Reroll', ranged: '–', bone_ids: [2, 2],
    origin: 'Core Game', count: '2', skill_ids: [16, 28],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Zaporavo.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zaporavo.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZaporavoToken.png' },

  # Monsters
  { name: 'Dark Demon', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee: '3 Red-Reroll', ranged: '–', bone_ids: [2, 2, 2],
    origin: 'Core Game', count: '2', skill_ids: [10, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/DarkDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DarkDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DarkDemonToken.png' },

  { name: 'Giant Snake', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee: '3 Orange-Reroll', ranged: '–', bone_ids: [4, 4, 4],
    origin: 'Core Game', count: '2', skill_ids: [10, 11],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantSnake.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSnake.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSnakeToken.png' },

  { name: 'Khosatral Khel', description: '',
    role: 'Monster', move: '3', armor: '12',
    melee: '3 Red', ranged: '–', bone_ids: [1, 1, 1],
    origin: 'Core Game', count: '2', skill_ids: [4, 11],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KhosatralKhel.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhosatralKhel.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhosatralKhelToken.png' },

  { name: 'Outer Dark Demon', description: '',
    role: 'Monster', move: '8', armor: '3',
    melee: '2 Red-Reroll', ranged: '–', bone_ids: [2, 2],
    origin: 'Core Game', count: '2', skill_ids: [12, 18],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/OuterDarkDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/OuterDarkDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/OuterDarkDemonToken.png' },

  { name: 'Thak', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee: '2 Red-Reroll', ranged: '–', bone_ids: [2, 2],
    origin: 'Core Game', count: '2', skill_ids: [10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thak.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thak.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThakToken.png' },

  # Ally
  { name: "Bêlit's Guards", description: '',
    role: 'Ally', move: '3', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'Core Game', count: '1', skill_ids: [16, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BelitsGuards.jpg',
    tile_image: "https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BelitsGuards.png",
    token_image: '' },

  { name: 'Princess', description: '',
    role: 'Ally', move: '2', armor: '0',
    melee: '–', ranged: '–', bone_ids: [],
    origin: 'Core Game', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Princess.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Princess.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PrincessToken.png' },

  # Minions
  { name: 'Bossonian Archers', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '–', ranged: '2 Yellow-Reroll', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [8],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianArchers.png',
    token_image: '' },

  { name: 'Bossonian Archers - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '–', ranged: '2 Yellow-Reroll', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [8],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianArchersPurple.png',
    token_image: '' },

  { name: 'Bossonian Guards', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuards.png',
    token_image: '' },

  { name: 'Bossonian Guards - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsBlue.png',
    token_image: '' },

  { name: 'Bossonian Guards - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsGreen.png',
    token_image: '' },

  { name: 'Bossonian Guards - Orange', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsOrange.png',
    token_image: '' },

  { name: 'Bossonian Guards - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsPurple.png',
    token_image: '' },

  { name: 'Bossonian Guards - Red', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Core Game', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BossonianGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BossonianGuardsRed.png',
    token_image: '' },

  { name: 'Hyenas', description: '',
    role: 'Minion', move: '5', armor: '0', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '2', skill_ids: [12, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Hyenas.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hyenas.png',
    token_image: '' },

  { name: 'Pict Hunters', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHunters.png',
    token_image: '' },

  { name: 'Pict Hunters - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersBlue.png',
    token_image: '' },

  { name: 'Pict Hunters - Green', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersGreen.png',
    token_image: '' },

  { name: 'Pict Hunters - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersOrange.png',
    token_image: '' },

  { name: 'Pict Hunters - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Core Game', count: '1', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictHuntersRed.png',
    token_image: '' },

  { name: 'Pict Warriors - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: 'Red-Reroll', ranged: '–', bone_ids: [2],
    origin: 'Core Game', count: '1', skill_ids: [10, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictWarriorsPurple.png',
    token_image: '' },

  { name: 'Pirates', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pirates.png',
    token_image: '' },

  { name: 'Pirates - Blue', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesBlue.png',
    token_image: '' },

  { name: 'Pirates - Green', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesGreen.png',
    token_image: '' },

  { name: 'Pirates - Orange', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesOrange.png',
    token_image: '' },

  { name: 'Pirates - Purple', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesPurple.png',
    token_image: '' },

  { name: 'Pirates - Red', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Core Game', count: '1', skill_ids: [13, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesRed.png',
    token_image: '' },

  ## King Pledge
  # Monster
  { name: 'Thog', description: '',
    role: 'Monster', move: '1', armor: '3',
    melee: '3 Red-Reroll', ranged: '–', bone_ids: [2, 2, 2],
    origin: 'King Pledge', count: '2', skill_ids: [14, 25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thog.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thog.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThogToken.png' },

  { name: 'Thog - Alt', description: '',
    role: 'Monster', move: '1', armor: '3',
    melee: '3 Red-Reroll', ranged: '–', bone_ids: [2, 2, 2],
    origin: 'King Pledge', count: '2', skill_ids: [3, 25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thog.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThogAlt.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThogToken.png' },

  # Allies
  { name: 'Conan’s Lion', description: '',
    role: 'Ally', move: '4', armor: '3', cost: '4',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'King Pledge', count: '1', skill_ids: [16, 17],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AmaraLion.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ConansLion.png',
    token_image: '' },

  { name: 'Zelata’s Wolf', description: '',
    role: 'Ally', move: '5', armor: '2', cost: '4',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'King Pledge', count: '1', skill_ids: [29, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZelataWolf.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZelatasWolf.png',
    token_image: '' },

  # Minions
  { name: 'Mummies', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Mummies.png',
    token_image: '' },

  { name: 'Mummies - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesBlue.png',
    token_image: '' },

  { name: 'Mummies - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesGreen.png',
    token_image: '' },

  { name: 'Mummies - Orange', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesOrange.png',
    token_image: '' },

  { name: 'Mummies - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'King Pledge', count: '1', skill_ids: [26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesPurple.png',
    token_image: '' },

  { name: 'Skeletons', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Skeletons.png',
    token_image: '' },

  { name: 'Skeletons - Green', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsGreen.png',
    token_image: '' },

  { name: 'Skeletons - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsBlue.png',
    token_image: '' },

  { name: 'Skeletons - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsOrange.png',
    token_image: '' },

  { name: 'Skeletons - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsPurple.png',
    token_image: '' },

  { name: 'Skeletons - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: 'Orange-Reroll', ranged: '–', bone_ids: [4],
    origin: 'King Pledge', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsRed.png',
    token_image: '' },

  ## Stretch Goal Tiles
  #  Event Tiles
  { name: 'Event 3', description: '',
    role: 'Event', move: '–', armor: '–',
    melee: '–', ranged: '–', bone_ids: [],
    origin: 'Stretch Goal', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event2.png',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Event2.png',
    token_image: '' },

  # Leaders
  { name: 'Ageera', description: 'Witch Hunter Finder',
    role: 'Leader', move: '3', armor: '2',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [16, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Ageera.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Ageera.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AgeeraToken.png' },

  { name: 'Akivasha', description: 'Stygian Priestess turned Vampire',
    role: 'Leader', move: '2', armor: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [6, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Akivasha.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Akivasha.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AkivashaToken.png' },

  { name: 'Constantius', description: 'The Falcon',
    role: 'Leader', move: '3', armor: '3',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [7, 28],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Constantius.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Constantius.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ConstantiusToken.png' },

  { name: 'Gitara', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee: '3 Yellow-Reroll', ranged: '–', bone_ids: [6, 6, 6],
    origin: 'Stretch Goal', count: '2', skill_ids: [17, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Gitara.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Gitara.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GitaraToken.png' },

  { name: 'Hyperborean Primitive', description: '',
    role: 'Leader', move: '3', armor: '3',
    melee: '2 Orange, Yellow', ranged: '–', bone_ids: [3, 3, 5],
    origin: 'Stretch Goal', count: '2', skill_ids: [26, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/HyperboreanPrimitive.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HyperboreanPrimitive.png' ,
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HyperboreanPrimitiveToken.png' },

  { name: 'Khemsa', description: 'A Black Circle Adept',
    role: 'Leader', move: '2', armor: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Khemsa.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Khemsa.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhemsaToken.png' },

  { name: 'Natohk', description: 'Stygian Sorceror Thugra Khotan',
    role: 'Leader', move: '3', armor: '2',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Stretch Goal', count: '2', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Natohk.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Natohk.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/NatohkToken.png' },

  { name: 'Warlock', description: '',
    role: 'Leader', move: '2', armor: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [32, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Warlock.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Warlock.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/WarlockToken.png' },

  # Heroes
  { name: 'Amboola', description: 'A Kushite Commander',
    role: 'Hero', move: '2', armor: '3',
    melee: '2 Orange-Reroll', ranged: '–', bone_ids: [4, 4],
    origin: 'Stretch Goal', count: '1', skill_ids: [5, 28,],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Amboola.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Amboola.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AmboolaToken.png' },

  { name: 'Balthus', description: 'A scout and a deadeye shot',
    role: 'Hero', move: '3', armor: '1',
    melee: '–', ranged: 'Red-Reroll, Orange-Reroll', bone_ids: [2, 4],
    origin: 'Stretch Goal', count: '1', skill_ids: [8, 9],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Balthus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Balthus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BalthusToken.png' },

  { name: 'Bêlit', description: 'Queen of the Black Coast',
    role: 'Hero', move: '3', armor: '1',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [6, 32],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Belit.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Belit.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BelitToken.png' },

  { name: 'Conan', description: '',
    role: 'Hero', move: '3', armor: '3',
    melee: '3 Red', ranged: '–', bone_ids: [1, 1, 1],
    origin: 'Stretch Goal', count: '2', skill_ids: [4, 11],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Conan.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Conan.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ConanToken.png' },

  { name: 'Hadrathus', description: '',
    role: 'Hero', move: '2', armor: '2',
    melee: '–', ranged: '2 Yellow', bone_ids: [5, 5],
    origin: 'Stretch Goal', count: '1', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Hadrathus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Hadrathus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HadrathusToken.png' },

  { name: 'Kerim Shah', description: 'A Turanian Prince',
    role: 'Hero', move: '2', armor: '2',
    melee: '–', ranged: '2 Orange', bone_ids: [3, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [9, 32],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KerimShah.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KerimShah.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KerimShahToken.png' },

  { name: "N'Gora", description: '',
    role: 'Hero', move: '2', armor: '3',
    melee: '–', ranged: '2 Red', bone_ids: [1, 1],
    origin: 'Stretch Goal', count: '1', skill_ids: [8, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/NGora.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/NGora.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/NGoraToken.png' },

  { name: 'Olgerd Vladislav', description: 'The Tiger',
    role: 'Hero', move: '2', armor: '3',
    melee: '2 Red-Reroll', ranged: '–', bone_ids: [2, 2],
    origin: 'Stretch Goal', count: '1', skill_ids: [4, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/OlgerdVladislav.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/OlgerdVladislav.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/OlgerdVladislavToken.png' },

  { name: 'Pallantides', description: 'Captain of the Black Dragons',
    role: 'Hero', move: '2', armor: '3',
    melee: 'Red-Reroll, Red', ranged: '–', bone_ids: [2, 1],
    origin: 'Stretch Goal', count: '1', skill_ids: [28, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pallantides.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Pallantides.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PallantidesToken.png' },

  { name: 'Shevatas', description: '',
    role: 'Hero', move: '3', armor: '2',
    melee: '–', ranged: '2 Orange', bone_ids: [3, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [12, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shevatas.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shevatas.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShevatasToken.png' },

  { name: 'Taurus', description: 'Prince of Thieves',
    role: 'Hero', move: '3', armor: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [5, 12],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Taurus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Taurus.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/TaurusToken.png' },

  { name: 'Valeria', description: '',
    role: 'Hero', move: '3', armor: '2',
    melee: '2 Orange-Reroll', ranged: '–', bone_ids: [4, 4],
    origin: 'Stretch Goal', count: '1', skill_ids: [7, 17],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Valeria.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Valeria.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ValeriaToken.png' },

  { name: 'Zelata', description: '',
    role: 'Hero', move: '2', armor: '1',
    melee: 'Yellow-Reroll, Yellow', ranged: '–', bone_ids: [6, 5],
    origin: 'Stretch Goal', count: '1', skill_ids: [28, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Zelata.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Zelata.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ZelataToken.png' },

  # Ally
  { name: 'Camel', description: 'Punch a camel',
    role: 'Ally', move: '4', armor: '2',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Stretch Goal', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Camel.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Camel.png',
    token_image: '' },

  { name: 'Kothian Archer', description: '',
    role: 'Ally', move: '3', armor: '2',
    melee: '–', ranged: 'Red', bone_ids: [1],
    origin: 'Stretch Goal', count: '1', skill_ids: [8, 9],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KothianArcher.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KothianArcher.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KothianArcherToken.png' },

  { name: 'Slasher', description: 'Balthus’ dog and ally',
    role: 'Ally', move: '5', armor: '3',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [12, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Slasher.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Slasher.png',
    token_image: '' },

  # Monsters
  { name: 'Bone Golem', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee: '3 Red', ranged: '–', bone_ids: [1, 1, 1],
    origin: 'Stretch Goal', count: '2', skill_ids: [11, 25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BoneGolem.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BoneGolem.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BoneGolemToken.png' },

  { name: 'Forest Demon', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee: '3 Orange', ranged: '–', bone_ids: [3, 3, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [5, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ForestDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ForestDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ForestDemonToken.png' },

  { name: 'Giant Scorpion', description: '',
    role: 'Monster', move: '3', armor: '2',
    melee: '3 Orange', ranged: '–', bone_ids: [3, 3, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [27],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantScorpion.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantScorpion.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantScorpionToken.png' },

  { name: 'Giant Spider', description: '',
    role: 'Monster', move: '4', armor: '2',
    melee: 'Red-Reroll, 2 Yellow', ranged: '–', bone_ids: [2, 5, 5],
    origin: 'Stretch Goal', count: '2', skill_ids: [15, 19],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantSpider.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSpider.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantSpiderToken.png' },

  { name: 'Gray Man-Ape', description: '',
    role: 'Monster', move: '3', armor: '3',
    melee: 'Red, 2 Orange', ranged: '–', bone_ids: [1, 3, 3],
    origin: 'Stretch Goal', count: '2', skill_ids: [10, 19],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GrayManApe.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GrayManApe.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GrayManApeToken.png' },

  { name: 'Swamp Demon', description: '',
    role: 'Monster', move: '2', armor: '2',
    melee: '2 Red-Reroll, Orange-Reroll', ranged: '–', bone_ids: [2, 2, 4],
    origin: 'Stretch Goal', count: '2', skill_ids: [25, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/SwampDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SwampDemon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SwampDemonToken.png' },

  { name: 'Thaug', description: '',
    role: 'Monster', move: '0', armor: '8',
    melee: '4 Red-Reroll', ranged: '–', bone_ids: [2, 2, 2, 2],
    origin: 'Stretch Goal', count: '2', skill_ids: [25, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Thaug.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Thaug.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThaugToken.png' },

  # Minions
  { name: 'Mummies - Alt', description: '',
    role: 'Minion', move: '2', armor: '3', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesAlt.png',
    token_image: '' },

  { name: 'Mummies - Blue Alt', description: '',
    role: 'Minion', move: '2', armor: '3', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Mummies.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/MummiesBlueAlt.png',
    token_image: '' },

  { name: 'Pict Archers', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee: '–', ranged: 'Yellow, Yellow-Reroll', bone_ids: [5, 6],
    origin: 'Stretch Goal', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictArchers.png',
    token_image: '' },

  { name: 'Pict Archers - Orange', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee: '–', ranged: 'Yellow, Yellow-Reroll', bone_ids: [5, 6],
    origin: 'Stretch Goal', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictArchers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictArchersOrange.png',
    token_image: '' },

  { name: 'Pict Warriors', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: 'Red-Reroll', ranged: '–', bone_ids: [2],
    origin: 'Stretch Goal', count: '1', skill_ids: [10, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PictWarriors.png',
    token_image: '' },

  { name: 'Pirates - Alt', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: '2 Yellow', ranged: '–', bone_ids: [5, 5],
    origin: 'Stretch Goal', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesAlt.png',
    token_image: '' },

  { name: 'Pirates - Orange Alt', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: '2 Yellow', ranged: '–', bone_ids: [5, 5],
    origin: 'Stretch Goal', count: '1', skill_ids: [16, 30],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Pirates.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/PiratesOrangeAlt.png',
    token_image: '' },

  { name: 'Skeletons - Alt', description: '',
    role: 'Minion', move: '2', armor: '0', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Stretch Goal', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsAlt.png',
    token_image: '' },

  { name: 'Skeletons - Red Alt', description: '',
    role: 'Minion', move: '2', armor: '0', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Stretch Goal', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skeletons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkeletonsRedAlt.png',
    token_image: '' },

  { name: 'Tentacles', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Tentacles.png',
    token_image: '' },

  { name: 'Tentacles - Blue', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/TentaclesBlue.png',
    token_image: '' },

  { name: 'Tentacles - Orange', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/TentaclesOrange.png',
    token_image: '' },

  { name: 'Tentacles - Red', description: '',
    role: 'Minion', move: '0', armor: '2', cost: '2',
    melee: 'Orange-Reroll, Orange', ranged: '–', bone_ids: [4, 3],
    origin: 'Stretch Goal', count: '1', skill_ids: [1, 3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Tentacles.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/TentaclesRed.png',
    token_image: '' },


  ## Add-Ons
  # Baal Pteor
  { name: 'Baal Pteor', description: '',
    role: 'Leader', move: '2', armor: '3',
    melee: 'Red-Reroll, 2 Red', ranged: '–', bone_ids: [2, 1, 1],
    origin: 'Baal Pteor', count: '2', skill_ids: [10, 5],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BaalPteor.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BaalPteor.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BaalPteorToken.png' },

  # Black Dragons
  { name: 'Black Dragons', description: "King Conan's personal bodyguard",
    role: 'Ally', move: '2', armor: '2',
    melee: 'Red-Reroll', ranged: '–', bone_ids: [2],
    origin: 'Black Dragons', count: '1', skill_ids: [7, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BlackDragons.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BlackDragons.png',
    token_image: '' },

  # Black Ones
  { name: 'The Black Ones', description: "",
    role: 'Minions', move: '3', armor: '3',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Black Ones', count: '1', skill_ids: [5, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BlackOnes.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BlackOnes.png',
    token_image: '' },

  { name: 'The Black Ones - Green', description: "",
    role: 'Minions', move: '3', armor: '3',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Black Ones', count: '1', skill_ids: [5, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BlackOnes.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BlackOnesGreen.png',
    token_image: '' },

  { name: 'The Black Ones - Purple', description: "",
    role: 'Minions', move: '3', armor: '3',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Black Ones', count: '1', skill_ids: [5, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/BlackOnes.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/BlackOnesPurple.png',
    token_image: '' },

  # Crossbowmen
  { name: 'Crossbowmen', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee: '–', ranged: 'Red', bone_ids: [1],
    origin: 'Crossbowmen', count: '1', skill_ids: [8, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crossbowmen.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crossbowmen.png',
    token_image: '' },

  { name: 'Crossbowmen - Green', description: 'An elite troop of sharpshooters',
    role: 'Minion', move: '2', armor: '0', cost: '3',
    melee: '–', ranged: 'Red-Reroll', bone_ids: [2],
    origin: 'Crossbowmen', count: '1', skill_ids: [8, 9],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crossbowmen.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CrossbowmenGreen.png',
    token_image: '' },

  { name: 'Crossbowmen - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '2',
    melee: '–', ranged: 'Red', bone_ids: [1],
    origin: 'Crossbowmen', count: '1', skill_ids: [8, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crossbowmen.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CrossbowmenRed.png',
    token_image: '' },

  # Demon of the Earth
  { name: 'Demon of the Earth', description: '',
    role: 'Monster', move: '2', armor: '3',
    melee: '4 Orange', ranged: '–', bone_ids: [3, 3, 3, 3],
    origin: 'Demon of the Earth', count: '2', skill_ids: [11, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/DemonEarth.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DemonEarth.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DemonEarth.png' },

  # Dragon
  { name: 'Dragon', description: '',
    role: 'Monster', move: '3', armor: '5',
    melee: '4 Red-Reroll', ranged: '–', bone_ids: [2, 2, 2, 2],
    origin: 'Dragon', count: '2', skill_ids: [11, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Dragon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Dragon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DragonToken.png' },

  # Giant Wolves
  { name: 'Giant Wolves', description: '',
    role: 'Minion', move: '5', armor: '1', cost: '2',
    melee: 'Red', ranged: '–', bone_ids: [1],
    origin: 'Giant Wolves', count: '3', skill_ids: [12, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZelataWolf.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantWolves.png',
    token_image: '' },

  # Sabertooth Tiger
  { name: 'Sabertooth Tiger', description: '',
    role: 'Monster', move: '4', armor: '1',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Sabertooth Tiger', count: '2', skill_ids: [16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/SabertoothTiger.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SabertoothTiger.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SabertoothTigerToken.png' },

  # Witch Hunters Add-Ons
  { name: 'Afari', description: 'Witch Hunter Warlord',
    role: 'Leader', move: '2', armor: '3',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [5, 7],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Afari.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Afari.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AfariToken.png' },

  { name: 'Ghayoor', description: 'Witch Hunter Bodyguard',
    role: 'Leader', move: '2', armor: '3',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [5, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Ghayoor.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Ghayoor.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GhayoorToken.png' },

  { name: 'Shafiah', description: 'Witch Hunter Bodyguard',
    role: 'Leader', move: '2', armor: '3',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [5, 29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shafiah.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shafiah.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShafiahToken.png' },

  { name: 'Shubba', description: 'Witch Hunter Sorcerer',
    role: 'Leader', move: '2', armor: '1',
    melee: '2 Yellow', ranged: '–', bone_ids: [5, 5],
    origin: 'Kushite Witch Hunters', count: '1', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Shubba.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Shubba.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShubbaToken.png' },

  # Vanir Valkyrie
  { name: 'Vanir Valkyrie', description: 'Not Red Sonja',
    role: 'Hero', move: '3', armor: '3',
    melee: '3 Orange-Reroll', ranged: '–', bone_ids: [4, 4, 4],
    origin: 'Vanir Valkyrie', count: '2', skill_ids: [5, 12],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirValkyrie.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirValkyrie.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirValkyrieToken.png' },

  # Paolo Parente Guest Box
  { name: 'Salome', description: 'Taramis’ Evil Sister',
    role: 'Leader', move: '2', armor: '1',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Paolo Parente Box', count: '2', skill_ids: [33, 32],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Taramis.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Salome.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SalomeToken.png' },


  ## Expansions
  # Nordheim Expansion
  { name: 'Atali', description: 'The Frost-Giant’s Daughter',
    role: 'Leader', move: '3', armor: '0',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Nordheim Expansion', count: '3', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Atali.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Atali.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AtaliToken.png' },

  { name: 'Yazdigerd', description: '',
    role: 'Leader', move: '2', armor: '2',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Nordheim Expansion', count: '2', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Skuthus.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Yazdigerd.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SkuthusToken.png' },

  { name: 'Nijgor', description: 'Atali’s Brother',
    role: 'Monster', move: '3', armor: '1',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'Nordheim Expansion', count: '2', skill_ids: [25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Nijgor.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Nijgor.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/NijgorToken.png' },

  { name: 'Seski', description: 'Atali’s Brother',
    role: 'Monster', move: '2', armor: '2',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'Nordheim Expansion', count: '2', skill_ids: [25],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Seski.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Seski.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/SeskiToken.png' },

  { name: 'Vanir Warriors', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirWarriors.png',
    token_image: '' },

  { name: 'Vanir Warriors - Blue', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [5],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirWarriorsBlue.png',
    token_image: '' },

  { name: 'Vanir Warriors - Purple', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow-Reroll', ranged: '–', bone_ids: [6, 6],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [5],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirWarriorsPurple.png',
    token_image: '' },

  { name: 'Vanir Zombies - Green', description: '',
    role: 'Minion', move: '1', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirZombiesGreen.png',
    token_image: '' },

  { name: 'Vanir Zombies - Red', description: '',
    role: 'Minion', move: '1', armor: '1', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [3],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/VanirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirZombiesRed.png',
    token_image: '' },

  { name: 'Vanir Primitives', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirPrimitives.png',
    token_image: '' },

  { name: 'Vanir Primitives - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/PictHunters.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/VanirPrimitivesRed.png',
    token_image: '' },

  { name: 'Crows', description: '',
    role: 'Minion', move: '5', armor: '1', cost: '1',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [18, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crows.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Crows.png',
    token_image: '' },

  { name: 'Crows - Red', description: '',
    role: 'Minion', move: '5', armor: '1', cost: '1',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [18, 26],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Crows.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/CrowsRed.png',
    token_image: '' },

  { name: 'Wolves', description: '',
    role: 'Minion', move: '5', armor: '0', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [12, 16],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ZelataWolf.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Wolves.png',
    token_image: '' },

  { name: 'Aesir Zombies - Purple', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '3',
    melee: 'Red', ranged: '–', bone_ids: [1],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [7, 10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AesirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AesirZombiesPurple.png',
    token_image: '' },

  { name: 'Aesir Warriors', description: '',
    role: 'Ally', move: '2', armor: '2', cost: '1',
    melee: 'Orange, Yellow', ranged: '–', bone_ids: [3, 5],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AesirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AesirWarriors.png',
    token_image: '' },

  { name: 'Aesir Warriors - Red', description: '',
    role: 'Ally', move: '2', armor: '0', cost: '1',
    melee: 'Orange', ranged: '–', bone_ids: [3],
    origin: 'Nordheim Expansion', count: '1', skill_ids: [12],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/AesirWarriors.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AesirWarriorsRed.png',
    token_image: '' },

  # Khitai Expansion
  { name: 'Shuang Mian', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Khitai Expansion', count: '2', skill_ids: [22, 33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ShuangMian.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShuangMian.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ShuangMianToken.png' },

  { name: 'Evil Hound', description: '',
    role: 'Monster', move: '2', armor: '2',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'Khitai Expansion', count: '2', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/DarkDemon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/EvilHound.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/DarkDemonToken.png' },

  { name: 'Khitan Guards', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow', ranged: '–', bone_ids: [5, 5],
    origin: 'Khitai Expansion', count: '1', skill_ids: [10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KhitanGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhitanGuards.png',
    token_image: '' },

  { name: 'Khitan Guards - Red', description: '',
    role: 'Minion', move: '2', armor: '1', cost: '1',
    melee: '2 Yellow', ranged: '–', bone_ids: [5, 5],
    origin: 'Khitai Expansion', count: '1', skill_ids: [10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/KhitanGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/KhitanGuardsRed.png',
    token_image: '' },

  { name: 'Honor Guards', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Khitai Expansion', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/HonorGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HonorGuards.png',
    token_image: '' },

  { name: 'Honor Guards - Green', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '2',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Khitai Expansion', count: '1', skill_ids: [29],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/HonorGuards.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/HonorGuardsGreen.png',
    token_image: '' },

  { name: 'Javelin Throwers', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '2',
    melee: '–', ranged: '2 Orange', bone_ids: [3, 3],
    origin: 'Khitai Expansion', count: '1', skill_ids: [8],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/JavelinThrowers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/JavelinThrowers.png',
    token_image: '' },

  { name: 'Javelin Throwers - Purple', description: '',
    role: 'Minion', move: '3', armor: '1', cost: '2',
    melee: '–', ranged: '2 Orange', bone_ids: [3, 3],
    origin: 'Khitai Expansion', count: '1', skill_ids: [8],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/JavelinThrowers.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/JavelinThrowersPurple.png',
    token_image: '' },

  { name: 'Foo Dogs', description: '',
    role: 'Minion', move: '5', armor: '2', cost: '1',
    melee: '2 Yellow', ranged: '–', bone_ids: [5, 5],
    origin: 'Khitai Expansion', count: '2', skill_ids: [7],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/FooDogs.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/FooDogs.png',
    token_image: '' },

  # Stygia Expansion
  { name: 'Thot-Amon', description: '',
    role: 'Leader', move: '2', armor: '1',
    melee: '2 Orange', ranged: '–', bone_ids: [3, 3],
    origin: 'Stygia Expansion', count: '2', skill_ids: [33],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ThotAmon.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThotAmon.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ThotAmonToken.png' },

  { name: 'Scorpion Broodmother', description: '',
    role: 'Monster', move: '2', armor: '3',
    melee: 'Red, Orange, Yellow', ranged: '–', bone_ids: [1, 3, 5],
    origin: 'Stygia Expansion', count: '2', skill_ids: [10],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/ScorpionBroodmother.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ScorpionBroodmother.png',
    token_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/ScorpionBroodmotherToken.png' },

  { name: 'Giant Scorpions', description: '',
    role: 'Minion', move: '4', armor: '0',
    melee: 'Yellow', ranged: '–', bone_ids: [5],
    origin: 'Stygia Expansion', count: '3', skill_ids: [27],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/GiantScorpions.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/GiantScorpions.png',
    token_image: '' },

  { name: 'Eternal Guard', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Stygia Expansion', count: '2', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/EternalGuard.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/EternalGuard.png',
    token_image: '' },

  { name: 'Eternal Guard - Blue', description: '',
    role: 'Minion', move: '2', armor: '2', cost: '1',
    melee: 'Red, Orange', ranged: '–', bone_ids: [1, 3],
    origin: 'Stygia Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/EternalGuard.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/EternalGuardBlue.png',
    token_image: '' },

  { name: 'Assassins', description: '',
    role: 'Minion', move: '3', armor: '0', cost: '2',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'Stygia Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Assassins.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/Assassins.png',
    token_image: '' },

  { name: 'Assassins  - Red', description: '',
    role: 'Minion', move: '3', armor: '0',
    melee: '2 Red', ranged: '–', bone_ids: [1, 1],
    origin: 'Stygia Expansion', count: '1', skill_ids: [],
    figure_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/figures/Assassins.jpg',
    tile_image: 'https://s3-us-west-2.amazonaws.com/drabelpdx/Conan/tiles/AssassinsRed.png',
    token_image: '' }

])
