# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  items = Item.create([
    { name: 'Battle Axe', encumberance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Red-Reroll', ranged_dice: 'Red-Reroll Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Dagger', encumberance: '1', origin: 'Core Game', count: '2',
      armor: '', melee_dice: 'Yellow', ranged_dice: 'Yellow Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Javelin', encumberance: '1', origin: 'Core Game', count: '2',
      armor: '', melee_dice: '', ranged_dice: 'Red Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Crossbow', encumberance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Red',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Explosive Orb', encumberance: '1', origin: 'Core Game', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '2 Red Area' },
    { name: 'Yuetshi Knife', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: 'Orange Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: "Conan's Sword", encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange', ranged_dice: 'Orange Throw',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Halberd', encumberance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '2 Red', ranged_dice: '',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Bossonian Bow', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Orange',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Sword', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: '',
      defense_dice: 'Yellow-Reroll', manipulation_dice: '' },
    { name: 'Parrying Dagger', encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Yellow-Reroll', ranged_dice: 'Yellow-Reroll Throw',
      defense_dice: 'Yellow-Reroll', manipulation_dice: '' },
    { name: 'Ornamental Spear', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: 'Orange-Reroll Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Tribal Mace', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: 'Orange Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Throwing Knives', encumberance: '0', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Yellow',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Kris', encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Yellow-Reroll', ranged_dice: 'Yellow Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Leather Armor', encumberance: '2', origin: 'Core Game', count: '2',
      armor: 'Yellow', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Chain Mail', encumberance: '5', origin: 'Core Game', count: '1',
      armor: 'Orange', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Scale Mail', encumberance: '5', origin: 'Core Game', count: '1',
      armor: 'Red', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Buckler', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Shield', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Tribal Shield', encumberance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Orange-Reroll', manipulation_dice: '' },
    { name: 'Life Potion', encumberance: '0', origin: 'Core Game', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Empty Chest', encumberance: '3', origin: 'Core Game', count: '2',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Xuthal Crown', encumberance: '1', origin: 'Core Game', count: '2',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: "Shaman's Staff", encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: "Sorcerer's Scepter", encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Stygian Artifact', encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Pictish Fetish', encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Tools', encumberance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Key', encumberance: '0', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Spellbook', encumberance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Axe', encumberance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '2 Yellow', ranged_dice: 'Orange Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Two-Handed Sword', encumberance: '3', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Red-Reroll', ranged_dice: '',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Turanian Sword', encumberance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: '',
      defense_dice: 'Orange-Reroll', manipulation_dice: '' },
    { name: 'Pirate Saber', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Orange', ranged_dice: 'Yellow Throw',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Sacrificial Dagger', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '2 Yellow', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Zingaran Bow', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Yellow-Reroll',
      defense_dice: '', manipulation_dice: '' },
    { name: "Mitra's Mace", encumberance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Red', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Stygian Scepter', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Red-Reroll', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Explosive Orb', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Zingaran Breastplate', encumberance: '3', origin: 'Stretch Goals', count: '1',
      armor: 'Yellow-Reroll', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: "Mita's Staff", encumberance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Yellow-Reroll', manipulation_dice: '' },
    { name: 'Black Staff', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Life Potion', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Pictish Drink', encumberance: '0', origin: 'Stretch Goals', count: '2',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Idol of Yag-Kosha', encumberance: '4', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Sacred Treasure', encumberance: '3', origin: 'Stretch Goals', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Phial', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Elixir', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Potion', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Unguent', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Ring', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Hyrkanian Mirror', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Heart of Ahriman', encumberance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Censer', encumberance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Cape', encumberance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Letters: A-E', encumberance: '', origin: 'Stretch Goals', count: '5',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Blank', encumberance: '', origin: 'Stretch Goals', count: '',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Leather Armor', encumberance: '2', origin: 'Nordheim Expansion', count: '1',
      armor: 'Yellow', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Aesir Blade', encumberance: '2', origin: 'Nordheim Expansion', count: '2',
      armor: '', melee_dice: 'Orange', ranged_dice: '',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Amulet Fragment', encumberance: '0', origin: 'Nordheim Expansion', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
  ])
