# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  items = Item.create([
    { name: 'Battle Axe', encumbrance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Red-Reroll', ranged_dice: 'Red-Reroll Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Dagger', encumbrance: '1', origin: 'Core Game', count: '2',
      armor: '', melee_dice: 'Yellow', ranged_dice: 'Yellow Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Javelin', encumbrance: '1', origin: 'Core Game', count: '2',
      armor: '', melee_dice: '', ranged_dice: 'Red Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Crossbow', encumbrance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Red',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Explosive Orb', encumbrance: '1', origin: 'Core Game', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '2 Red Area' },
    { name: 'Yuetshi Knife', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: 'Orange Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: "Conan’s Sword", encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange', ranged_dice: 'Orange Throw',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Halberd', encumbrance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '2 Red', ranged_dice: '',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Bossonian Bow', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Orange',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Sword', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: '',
      defense_dice: 'Yellow-Reroll', manipulation_dice: '' },
    { name: 'Parrying Dagger', encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Yellow-Reroll', ranged_dice: 'Yellow-Reroll Throw',
      defense_dice: 'Yellow-Reroll', manipulation_dice: '' },
    { name: 'Ornamental Spear', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: 'Orange-Reroll Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Tribal Mace', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: 'Orange Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Throwing Knives', encumbrance: '0', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Yellow',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Kris', encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: 'Yellow-Reroll', ranged_dice: 'Yellow Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Leather Armor', encumbrance: '2', origin: 'Core Game', count: '2',
      armor: 'Yellow', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Chain Mail', encumbrance: '5', origin: 'Core Game', count: '1',
      armor: 'Orange', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Scale Mail', encumbrance: '5', origin: 'Core Game', count: '1',
      armor: 'Red', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Buckler', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Shield', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Tribal Shield', encumbrance: '3', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Orange-Reroll', manipulation_dice: '' },
    { name: 'Life Potion', encumbrance: '0', origin: 'Core Game', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Empty Chest', encumbrance: '3', origin: 'Core Game', count: '2',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Xuthal Crown', encumbrance: '1', origin: 'Core Game', count: '2',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: "Shaman’s Staff", encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: "Sorcerer’s Scepter", encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Stygian Artifact', encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Pictish Fetish', encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Tools', encumbrance: '1', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Key', encumbrance: '0', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Spellbook', encumbrance: '2', origin: 'Core Game', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Axe', encumbrance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '2 Yellow', ranged_dice: 'Orange Throw',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Two-Handed Sword', encumbrance: '3', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Red-Reroll', ranged_dice: '',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Turanian Sword', encumbrance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Orange-Reroll', ranged_dice: '',
      defense_dice: 'Orange-Reroll', manipulation_dice: '' },
    { name: 'Pirate Saber', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Orange', ranged_dice: 'Yellow Throw',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Sacrificial Dagger', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '2 Yellow', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Zingaran Bow', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: 'Yellow-Reroll',
      defense_dice: '', manipulation_dice: '' },
    { name: "Mitra’s Mace", encumbrance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Red', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Stygian Scepter', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: 'Red-Reroll', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Explosive Orb', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Zingaran Breastplate', encumbrance: '3', origin: 'Stretch Goals', count: '1',
      armor: 'Yellow-Reroll', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: "Mita’s Staff", encumbrance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Yellow-Reroll', manipulation_dice: '' },
    { name: 'Black Staff', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: 'Yellow', manipulation_dice: '' },
    { name: 'Life Potion', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Pictish Drink', encumbrance: '0', origin: 'Stretch Goals', count: '2',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Idol of Yag-Kosha', encumbrance: '4', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Sacred Treasure', encumbrance: '3', origin: 'Stretch Goals', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Phial', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Elixir', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Potion', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Unguent', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Ring', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Hyrkanian Mirror', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Heart of Ahriman', encumbrance: '0', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Censer', encumbrance: '1', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Cape', encumbrance: '2', origin: 'Stretch Goals', count: '1',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Letters: A-E', encumbrance: '', origin: 'Stretch Goals', count: '5',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Blank', encumbrance: '', origin: 'Stretch Goals', count: '',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Leather Armor', encumbrance: '2', origin: 'Nordheim Expansion', count: '1',
      armor: 'Yellow', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
    { name: 'Aesir Blade', encumbrance: '2', origin: 'Nordheim Expansion', count: '2',
      armor: '', melee_dice: 'Orange', ranged_dice: '',
      defense_dice: 'Orange', manipulation_dice: '' },
    { name: 'Amulet Fragment', encumbrance: '0', origin: 'Nordheim Expansion', count: '3',
      armor: '', melee_dice: '', ranged_dice: '',
      defense_dice: '', manipulation_dice: '' },
  ])
